"""add user_vault table for chapter 6

Revision ID: 1b6772b5838d
Revises: 9946e9d19f17
Create Date: 2026-02-10 14:59:50.795473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6772b5838d'
down_revision: Union[str, Sequence[str], None] = '9946e9d19f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_name', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vaults_user_id'), 'user_vaults', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vaults_user_id'), table_name='user_vaults')
    op.drop_table('user_vaults')
    # ### end Alembic commands ###
