"""add_tenant_id_to_emails

Revision ID: 551091d80e6c
Revises: 1b6772b5838d
Create Date: 2026-02-12 03:28:43.901569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551091d80e6c'
down_revision: Union[str, Sequence[str], None] = '1b6772b5838d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_emails_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emails_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_column('tenant_id')
    # ### end Alembic commands ###
