"""Add Email fields

Revision ID: 9946e9d19f17
Revises: 621eb0ffdbd1
Create Date: 2026-02-10 03:55:57.783523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9946e9d19f17'
down_revision: Union[str, Sequence[str], None] = '621eb0ffdbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('emails', sa.Column('gmail_id', sa.String(), nullable=True))
    # op.add_column('emails', sa.Column('snippet', sa.String(), nullable=True))
    # op.add_column('emails', sa.Column('body_text', sa.String(), nullable=True))
    # op.add_column('emails', sa.Column('body_html', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_emails_gmail_id'), 'emails', ['gmail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_gmail_id'), table_name='emails')
    op.drop_column('emails', 'is_read')
    op.drop_column('emails', 'body_html')
    op.drop_column('emails', 'body_text')
    op.drop_column('emails', 'snippet')
    op.drop_column('emails', 'gmail_id')
    # ### end Alembic commands ###
